import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

final lightTheme = ThemeData(
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFE4C626),
      onPrimary: Color.fromARGB(255, 0, 0, 0),
      primaryContainer: Color(0xFFE9DDFF),
      onPrimaryContainer: Color(0xFF22005D),
      secondary: Color.fromARGB(255, 231, 231, 231),
      onSecondary: Color.fromARGB(255, 255, 255, 255),
      secondaryContainer: Color(0xFFE8DEF8),
      onSecondaryContainer: Color(0xFF1E192B),
      tertiary: Color(0xFF7E5260),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD9E3),
      onTertiaryContainer: Color(0xFF31101D),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      surface: Color(0xFFFFFBFF),
      onSurface: Color.fromARGB(255, 0, 0, 0),
      onSurfaceVariant: Color(0xFF49454E),
      outline: Color(0xFF7A757F),
      onInverseSurface: Color(0xFFF4EFF4),
      inverseSurface: Color(0xFF313033),
      inversePrimary: Color(0xFFCFBCFF),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFF6750A4),
      outlineVariant: Color(0xFFCAC4CF),
      scrim: Color(0xFF000000),
    ),
    textTheme: GoogleFonts.lexendDecaTextTheme(),
    useMaterial3: true,
    dividerTheme: const DividerThemeData(
      color: Colors.transparent,
    ));

final darkTheme = ThemeData(
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFE4C626),
    onPrimary: Color.fromARGB(255, 255, 255, 255),
    primaryContainer: Color(0xFF4F378A),
    onPrimaryContainer: Color(0xFFE9DDFF),
    secondary: Color(0xff222222),
    onSecondary: Color.fromARGB(255, 0, 0, 0),
    secondaryContainer: Color(0xFF4A4458),
    onSecondaryContainer: Color(0xFFE8DEF8),
    tertiary: Color(0xFFEFB8C8),
    onTertiary: Color(0xFF4A2532),
    tertiaryContainer: Color(0xFF633B48),
    onTertiaryContainer: Color(0xFFFFD9E3),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    //Cor de fundo
    surface: Color(0xff0E0E0E),
    onSurface: Color(0xFFE6E1E6),
    onSurfaceVariant: Color(0xFFCAC4CF),
    outline: Color(0xFF948F99),
    onInverseSurface: Color(0xFF1C1B1E),
    inverseSurface: Color(0xFFE6E1E6),
    inversePrimary: Color(0xFF6750A4),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFCFBCFF),
    outlineVariant: Color(0xFF49454E),
    scrim: Color(0xFF000000),
  ),
  textTheme: GoogleFonts.lexendDecaTextTheme(),
  useMaterial3: true,
  dividerTheme: const DividerThemeData(
    color: Colors.transparent,
  ),
);
